plugins:
  - jekyll-feed
  - jekyll-sitemap

title: Chemobrionics Database
author: Carlos Pimentel
languageCode: en-us

permalink: /chemobrionics/:year/:month/:day/:title:output_ext

feed:
  posts_limit: 100
