plugins:
  - jekyll-feed
  - jekyll-sitemap

title: Chemobrionics Database
author: Carlos Pimentel
languageCode: en-us

url: "https://cpimentelguerra.com/"
baseurl: "chemobrionics"

permalink: /:year/:month/:day/:title:output_ext

feed:
  posts_limit: 100
